In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv('HR_data.csv')
df.head(5)

,Employee Number,Attrition,Business Travel,Age Group,Department,Education Field,Employee Count,Gender,Job Role,Marital Status,...,Environment Satisfaction,Job Level,Job Satisfaction,Monthly Income,Total Working Years,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Curr Manager
0,1,Yes,Travel_Rarely,35 - 44,Sales,Life Sciences,1,Female,Sales Executive,Single,...,2,2,4,5993,8,1,6,4,0,5
1,2,No,Travel_Frequently,45 - 54,R&D,Life Sciences,1,Male,Research Scientist,Married,...,3,2,2,5130,10,3,10,7,1,7
2,3,Yes,Travel_Rarely,35 - 44,R&D,Other,1,Male,Laboratory Technician,Single,...,4,1,3,2090,7,3,0,0,0,0
3,4,No,Travel_Frequently,25 - 34,R&D,Life Sciences,1,Female,Research Scientist,Married,...,4,1,3,2909,8,3,8,7,3,0
4,5,No,Travel_Rarely,25 - 34,R&D,Medical,1,Male,Laboratory Technician,Married,...,1,1,2,3468,6,3,2,2,2,2

In [2]:
print("shape :",df.shape)
print("--------------------------------------")
print(df.info())
print("--------------------------------------")
print("Nulls :\n",df.isnull().sum())
print("--------------------------------------")
print("Duplicate :",df.duplicated().sum())

shape : (1470, 24)
--------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee Number             1470 non-null   int64
 1   Attrition                   1470 non-null   str
 2   Business Travel             1470 non-null   str
 3   Age Group                   1470 non-null   str
 4   Department                  1470 non-null   str
 5   Education Field             1470 non-null   str
 6   Employee Count              1470 non-null   int64
 7   Gender                      1470 non-null   str
 8   Job Role                    1470 non-null   str
 9   Marital Status              1470 non-null   str
 10  Over Time                   1470 non-null   str
 11  Age                         1470 non-null   int64
 12  Distance From Home          1470 non-null   int64
 13  Education                   1470 non-null   str
 14  Environment Satisfaction    1470 non-null   int64
 15  Job Level                   1470 non-null   int64
 16  Job Satisfaction            1470 non-null   int64
 17  Monthly Income              1470 non-null   int64
 18  Total Working Years         1470 non-null   int64
 19  Work Life Balance           1470 non-null   int64
 20  Years At Company            1470 non-null   int64
 21  Years In Current Role       1470 non-null   int64
 22  Years Since Last Promotion  1470 non-null   int64
 23  Years With Curr Manager     1470 non-null   int64
dtypes: int64(14), str(10)
memory usage: 275.8 KB
None
--------------------------------------
Nulls :
 Employee Number               0
Attrition                     0
Business Travel               0
Age Group                     0
Department                    0
Education Field               0
Employee Count                0
Gender                        0
Job Role                      0
Marital Status                0
Over Time                     0
Age                           0
Distance From Home            0
Education                     0
Environment Satisfaction      0
Job Level                     0
Job Satisfaction              0
Monthly Income                0
Total Working Years           0
Work Life Balance             0
Years At Company              0
Years In Current Role         0
Years Since Last Promotion    0
Years With Curr Manager       0
dtype: int64
--------------------------------------
Duplicate : 0

In [22]:
df.columns=df.columns.str.strip().str.replace(" ","_")

In [4]:
#drop useless column
#employee count column is 1 for every row -so no need to analytics use so drop it
if 'Employee_Count' in df.columns:
    df=df.drop(columns=['Employee_Count'])
print(df.columns)

Index(['Employee_Number', 'Attrition', 'Business_Travel', 'Age_Group',
       'Department', 'Education_Field', 'Gender', 'Job_Role', 'Marital_Status',
       'Over_Time', 'Age', 'Distance_From_Home', 'Education',
       'Environment_Satisfaction', 'Job_Level', 'Job_Satisfaction',
       'Monthly_Income', 'Total_Working_Years', 'Work_Life_Balance',
       'Years_At_Company', 'Years_In_Current_Role',
       'Years_Since_Last_Promotion', 'Years_With_Curr_Manager'],
      dtype='str')

In [5]:
# create new column income level
df['Income_Level']=pd.qcut(df['Monthly_Income'],q=4,labels=['Low','Medium','High','Very High'])

In [6]:
# tenure buckets
df['Tenure_Group']=pd.cut(df['Years_At_Company'],bins=[-1,2,5,10,20,100],labels=['0-2 years','3-5 years','6-10 years','11-20 years','20+ years'])

In [7]:
# Map numeric satisfaction to label
satisfaction_map={1:'Low',2:'Medium',3:'High',4:'Very High'}
df['Job_Satisfaction']=df['Job_Satisfaction'].map(satisfaction_map)
df['Environment_Satisfaction']=df['Environment_Satisfaction'].map(satisfaction_map)

,Employee_Number,Attrition,Business_Travel,Age_Group,Department,Education_Field,Gender,Job_Role,Marital_Status,Over_Time,...,Job_Satisfaction,Monthly_Income,Total_Working_Years,Work_Life_Balance,Years_At_Company,Years_In_Current_Role,Years_Since_Last_Promotion,Years_With_Curr_Manager,Income_Level,Tenure_Group
0,1,Yes,Travel_Rarely,35 - 44,Sales,Life Sciences,Female,Sales Executive,Single,Yes,...,Very High,5993,8,1,6,4,0,5,High,6-10 years
1,2,No,Travel_Frequently,45 - 54,R&D,Life Sciences,Male,Research Scientist,Married,No,...,Medium,5130,10,3,10,7,1,7,High,6-10 years
2,3,Yes,Travel_Rarely,35 - 44,R&D,Other,Male,Laboratory Technician,Single,Yes,...,High,2090,7,3,0,0,0,0,Low,0-2 years
3,4,No,Travel_Frequently,25 - 34,R&D,Life Sciences,Female,Research Scientist,Married,Yes,...,High,2909,8,3,8,7,3,0,Low,6-10 years
4,5,No,Travel_Rarely,25 - 34,R&D,Medical,Male,Laboratory Technician,Married,No,...,Medium,3468,6,3,2,2,2,2,Medium,0-2 years
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,1466,Yes,Non-Travel,25 - 34,R&D,Technical Degree,Male,Research Scientist,Married,Yes,...,Low,2307,5,3,5,2,3,0,Low,3-5 years
1466,1467,Yes,Travel_Frequently,25 - 34,R&D,Life Sciences,Male,Research Scientist,Single,Yes,...,Very High,2439,1,2,1,0,1,0,Low,0-2 years
1467,1468,Yes,Travel_Frequently,35 - 44,Sales,Other,Male,Sales Executive,Single,Yes,...,Very High,4581,13,4,11,9,6,7,Medium,11-20 years
1468,1469,Yes,Travel_Rarely,Under 25,R&D,Life Sciences,Male,Research Scientist,Single,Yes,...,Medium,2472,1,3,1,0,0,0,Low,0-2 years
1469,1470,Yes,Travel_Rarely,Under 25,Sales,Life Sciences,Male,Sales Representative,Divorced,Yes,...,Very High,2275,3,3,3,2,0,2,Low,3-5 years

In [12]:
#promotion risk flag -- year since last promotion vs years at a company
df['Promotion_Overdue']=(df['Years_Since_Last_Promotion']>=5).astype(int)
df[['Years_Since_Last_Promotion','Promotion_Overdue']]

      Years_Since_Last_Promotion  Promotion_Overdue
0                              0                  0
1                              1                  0
2                              0                  0
3                              3                  0
4                              2                  0
...                          ...                ...
1465                           3                  0
1466                           1                  0
1467                           6                  1
1468                           0                  0
1469                           0                  0

[1470 rows x 2 columns]

In [27]:
df['attrition_flag']=df['attrition'].map({'Yes':1,'No':0})

In [28]:
print("\n Cleaned shape:",df.shape)
print("--------------------------------------")
print(df.head())
print("--------------------------------------")
print(df.dtypes)

 Cleaned shape: (1470, 27)
--------------------------------------
   employee_number attrition    business_travel age_group department  \
0                1       Yes      Travel_Rarely   35 - 44      Sales
1                2        No  Travel_Frequently   45 - 54        R&D
2                3       Yes      Travel_Rarely   35 - 44        R&D
3                4        No  Travel_Frequently   25 - 34        R&D
4                5        No      Travel_Rarely   25 - 34        R&D

  education_field  gender               job_role marital_status over_time  \
0   Life Sciences  Female        Sales Executive         Single       Yes
1   Life Sciences    Male     Research Scientist        Married        No
2           Other    Male  Laboratory Technician         Single       Yes
3   Life Sciences  Female     Research Scientist        Married       Yes
4         Medical    Male  Laboratory Technician        Married        No

   ...  total_working_years  work_life_balance years_at_company  \
0  ...                    8                  1                6
1  ...                   10                  3               10
2  ...                    7                  3                0
3  ...                    8                  3                8
4  ...                    6                  3                2

  years_in_current_role  years_since_last_promotion years_with_curr_manager  \
0                     4                           0                       5
1                     7                           1                       7
2                     0                           0                       0
3                     7                           3                       0
4                     2                           2                       2

   income_level  tenure_group  promotion_overdue  attrition_flag
0          High    6-10 years                  0               1
1          High    6-10 years                  0               0
2           Low     0-2 years                  0               1
3           Low    6-10 years                  0               0
4        Medium     0-2 years                  0               0

[5 rows x 27 columns]
--------------------------------------
employee_number                  int64
attrition                          str
business_travel                    str
age_group                          str
department                         str
education_field                    str
gender                             str
job_role                           str
marital_status                     str
over_time                          str
age                              int64
distance_from_home               int64
education                          str
environment_satisfaction           str
job_level                        int64
job_satisfaction                   str
monthly_income                   int64
total_working_years              int64
work_life_balance                int64
years_at_company                 int64
years_in_current_role            int64
years_since_last_promotion       int64
years_with_curr_manager          int64
income_level                  category
tenure_group                  category
promotion_overdue                int64
attrition_flag                   int64
dtype: object

In [29]:
df.to_csv("HR_Attrition_cleaned.csv",index=False)

In [30]:
df.columns

Index(['employee_number', 'attrition', 'business_travel', 'age_group',
       'department', 'education_field', 'gender', 'job_role', 'marital_status',
       'over_time', 'age', 'distance_from_home', 'education',
       'environment_satisfaction', 'job_level', 'job_satisfaction',
       'monthly_income', 'total_working_years', 'work_life_balance',
       'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager', 'income_level',
       'tenure_group', 'promotion_overdue', 'attrition_flag'],
      dtype='str')

In [31]:
from sqlalchemy import create_engine

username="postgres"
password="nitin123"
host="localhost"
port="5432"
database="HR_Analytics"# database name you created in sql

engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name="hr_attrition"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"Data Successfully Loaded into table '{table_name}'in database'{database}'.")

Data Successfully Loaded into table 'hr_attrition'in database'HR_Analytics'.